import type { EndpointCatalogItem } from "@/lib/types";

export const endpointCatalog: EndpointCatalogItem[] = [
  {
    key: "frontend-customer-health",
    name: "Customer frontend health",
    component: "Customer Frontend",
    surface: "frontend",
    routePath: "/api/health",
    targetKind: "http",
    targetUrl: "http://frontend-customer:3000/api/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 10,
    notes: "Confirms the customer Next.js app is serving traffic.",
  },
  {
    key: "frontend-restaurant-health",
    name: "Restaurant frontend health",
    component: "Restaurant Frontend",
    surface: "frontend",
    routePath: "/api/health",
    targetKind: "http",
    targetUrl: "http://frontend-restaurant:3001/api/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 20,
  },
  {
    key: "frontend-driver-health",
    name: "Driver frontend health",
    component: "Driver Frontend",
    surface: "frontend",
    routePath: "/api/health",
    targetKind: "http",
    targetUrl: "http://frontend-driver:3002/api/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 30,
  },
  {
    key: "frontend-agent-health",
    name: "Support frontend health",
    component: "Support Frontend",
    surface: "frontend",
    routePath: "/api/health",
    targetKind: "http",
    targetUrl: "http://frontend-agent:3003/api/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 40,
  },
  {
    key: "api-gateway-health",
    name: "API gateway health",
    component: "Platform Backend",
    surface: "backend",
    routePath: "/health",
    targetKind: "http",
    targetUrl: "http://api-gateway:8080/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 50,
  },
  {
    key: "user-service-health",
    name: "User service health",
    component: "Platform Backend",
    surface: "backend",
    routePath: "/api/users/health",
    targetKind: "http",
    targetUrl: "http://user-service:8081/api/users/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 60,
  },
  {
    key: "restaurant-service-health",
    name: "Restaurant service health",
    component: "Platform Backend",
    surface: "backend",
    routePath: "/api/restaurants/health",
    targetKind: "http",
    targetUrl: "http://restaurant-service:8082/api/restaurants/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 70,
  },
  {
    key: "order-service-health",
    name: "Order service health",
    component: "Platform Backend",
    surface: "backend",
    routePath: "/api/orders/health",
    targetKind: "http",
    targetUrl: "http://order-service:8083/api/orders/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 80,
  },
  {
    key: "delivery-service-health",
    name: "Delivery service health",
    component: "Platform Backend",
    surface: "backend",
    routePath: "/api/delivery/health",
    targetKind: "http",
    targetUrl: "http://delivery-service:8084/api/delivery/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 90,
  },
  {
    key: "payment-service-health",
    name: "Payment service health",
    component: "Platform Backend",
    surface: "backend",
    routePath: "/api/payments/health",
    targetKind: "http",
    targetUrl: "http://payment-service:8085/api/payments/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 100,
  },
  {
    key: "notification-service-health",
    name: "Notification service health",
    component: "Platform Backend",
    surface: "backend",
    routePath: "/health",
    targetKind: "http",
    targetUrl: "http://notification-service:8086/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 110,
  },
  {
    key: "chat-service-health",
    name: "Chat service health",
    component: "Platform Backend",
    surface: "backend",
    routePath: "/health",
    targetKind: "http",
    targetUrl: "http://chat-service:8087/health",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 120,
  },
  {
    key: "gateway-restaurants-list",
    name: "Gateway public restaurants list",
    component: "Customer Backend Health",
    surface: "backend",
    routePath: "/api/restaurants?size=25",
    targetKind: "http",
    targetUrl: "http://api-gateway:8080/api/restaurants?size=25",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 130,
    notes: "Smoke-tests a real customer-facing public API through the gateway.",
  },
  {
    key: "postgres-health",
    name: "PostgreSQL connectivity",
    component: "Infrastructure",
    surface: "infrastructure",
    routePath: "postgresql://postgres:5432/zomato_health",
    targetKind: "database",
    targetUrl: "postgresql://postgres:5432/zomato_health",
    method: "PING",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 140,
  },
  {
    key: "redis-port-health",
    name: "Redis port availability",
    component: "Infrastructure",
    surface: "infrastructure",
    routePath: "tcp://redis:6379",
    targetKind: "tcp",
    targetUrl: "tcp://redis:6379",
    method: "PING",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 150,
  },
  {
    key: "rabbitmq-port-health",
    name: "RabbitMQ port availability",
    component: "Infrastructure",
    surface: "infrastructure",
    routePath: "tcp://rabbitmq:5672",
    targetKind: "tcp",
    targetUrl: "tcp://rabbitmq:5672",
    method: "PING",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 160,
  },
  {
    key: "mongodb-port-health",
    name: "MongoDB port availability",
    component: "Infrastructure",
    surface: "infrastructure",
    routePath: "tcp://mongodb:27017",
    targetKind: "tcp",
    targetUrl: "tcp://mongodb:27017",
    method: "PING",
    expectedStatusCodes: [200],
    executionMode: "live",
    requiresAuth: false,
    sequence: 170,
  },
  {
    key: "users-auth-login",
    name: "User login endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/users/auth/login",
    targetKind: "http",
    method: "POST",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: false,
    sequence: 210,
    notes: "Cataloged from the frontend auth flows. Skipped automatically to avoid mutating real auth state.",
    samplePayload: { email: "demo@zomato.local", password: "masked" },
  },
  {
    key: "users-auth-register",
    name: "User register endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/users/auth/register",
    targetKind: "http",
    method: "POST",
    expectedStatusCodes: [200, 201],
    executionMode: "catalog_only",
    requiresAuth: false,
    sequence: 220,
    samplePayload: { name: "Demo", email: "demo@zomato.local", role: "CUSTOMER" },
  },
  {
    key: "users-auth-me",
    name: "Current user profile endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/users/auth/me",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 230,
  },
  {
    key: "restaurants-list",
    name: "Restaurant listing endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/restaurants",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: false,
    sequence: 240,
  },
  {
    key: "restaurants-detail",
    name: "Restaurant detail endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/restaurants/:id",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: false,
    sequence: 250,
  },
  {
    key: "restaurants-menu",
    name: "Restaurant menu endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/restaurants/:id/menu",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: false,
    sequence: 260,
  },
  {
    key: "restaurants-reviews",
    name: "Restaurant reviews endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/restaurants/:id/reviews",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: false,
    sequence: 270,
  },
  {
    key: "restaurants-owner-profile",
    name: "Restaurant owner profile endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/restaurants/owner/me",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 280,
  },
  {
    key: "restaurants-owner-stats",
    name: "Restaurant owner stats endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/restaurants/owner/me/stats",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 290,
  },
  {
    key: "orders-create",
    name: "Create order endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/orders",
    targetKind: "http",
    method: "POST",
    expectedStatusCodes: [200, 201],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 300,
  },
  {
    key: "orders-my",
    name: "My orders endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/orders/my",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 310,
  },
  {
    key: "orders-detail",
    name: "Order detail endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/orders/:id",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 320,
  },
  {
    key: "orders-status",
    name: "Order status update endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/orders/:id/status",
    targetKind: "http",
    method: "PUT",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 330,
    samplePayload: { status: "DELIVERED" },
  },
  {
    key: "delivery-available",
    name: "Delivery availability endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/delivery/available",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 340,
  },
  {
    key: "delivery-active",
    name: "Active delivery endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/delivery/active",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 350,
  },
  {
    key: "delivery-history",
    name: "Delivery history endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/delivery/history",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 360,
  },
  {
    key: "delivery-stats",
    name: "Delivery stats endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/delivery/stats",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 370,
  },
  {
    key: "chat-chats-list",
    name: "Chat list endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/chat/chats",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 380,
  },
  {
    key: "chat-chat-messages",
    name: "Chat messages endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/chat/chats/:id/messages",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 390,
  },
  {
    key: "chat-incidents-list",
    name: "Support incidents endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/chat/incidents",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 400,
  },
  {
    key: "chat-incidents-stats",
    name: "Support incident stats endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/chat/incidents/stats",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 410,
  },
  {
    key: "payments-create",
    name: "Create payment endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/payments",
    targetKind: "http",
    method: "POST",
    expectedStatusCodes: [200, 201],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 420,
  },
  {
    key: "payments-detail",
    name: "Payment detail endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/payments/:id",
    targetKind: "http",
    method: "GET",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: true,
    sequence: 430,
  },
  {
    key: "payments-coupon-validate",
    name: "Coupon validation endpoint",
    component: "Endpoint Catalog",
    surface: "catalog",
    routePath: "/api/payments/coupons/validate",
    targetKind: "http",
    method: "POST",
    expectedStatusCodes: [200],
    executionMode: "catalog_only",
    requiresAuth: false,
    sequence: 440,
  },
];
